/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.integratedmodelling.klab.data;

@org.apache.avro.specific.AvroGenerated
public interface KlabData {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"KlabData\",\"namespace\":\"org.integratedmodelling.klab.data\",\"types\":[{\"type\":\"enum\",\"name\":\"Level\",\"symbols\":[\"INFO\",\"WARNING\",\"DEBUG\"]},{\"type\":\"record\",\"name\":\"Notification\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"},{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"level\",\"type\":\"Level\"}]},{\"type\":\"record\",\"name\":\"Scale\",\"fields\":[]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends KlabData {
    public static final org.apache.avro.Protocol PROTOCOL = org.integratedmodelling.klab.data.KlabData.PROTOCOL;
  }
}