package org.integratedmodelling.klab.runtime.kactors;

import java.util.concurrent.TimeUnit;
import org.integratedmodelling.klab.api.exceptions.KlabActorException;
import org.integratedmodelling.klab.api.knowledge.observation.scale.time.Time;
import org.integratedmodelling.klab.api.knowledge.observation.scale.time.TimeDuration;
import org.integratedmodelling.klab.api.knowledge.observation.scale.time.TimeInstant;
import org.integratedmodelling.klab.api.services.runtime.extension.Verb;
import org.integratedmodelling.klab.api.utils.Utils;
import org.integratedmodelling.klab.runtime.libraries.CoreActorLibrary;

///  # TO BE REMOVED - example translation of following k.Actors code:
///
///
/// ```

/// ```
////// behavior test.main;
/// ///
/// /// action main:
/// ///    emitter: sentence -> console.format("Emitter said %s", sentence)
/// ///
/// ///  // an emitter (fires periodically, no return, continues firing)
/// /// action emitter:
/// ///         timer.random(step=10.s): time -> fire "dio puto"
/// This must be created by the actor compiler and compiled to a .class internally.
/// Actors that do not return must be run within an asynchronous container to work
/// properly.
///
public class RuntimeAgentExample extends RuntimeAgentBase {

  public RuntimeAgentExample() {
    super(null, null);
  }

  /* This code is generated by the AgentCompiler*/
  @Override
  protected ExitValue main(AgentScope initialScope) {

    // TODO if there's a behavior, the specialized scope class should get it to
    // analyze and set up any further data structures (UI, test plan etc).

    // TODO install any @handle messages for external message call

    // compile call to main_0 if there's a main action
    if (!main_0(initialScope)) {
      return ExitValue.failure(new KlabActorException(this, "main action failed to execute"));
    }
    // TODO should catch exceptions and return ExitValue.failure(exception)

    // end of main(). This must exit and the actor remains active depending on exec mode
    return ExitValue.success(0);
  }

  /* This code is generated by the AgentCompiler after analyzing the behavior*/
  @Override
  public Verb.Type getAgentExecutionMode() {
    return Verb.Type.EMITTER;
  }

  /**
   * Named action <em>main</em> with id == 0 compiled from line 10 of <em>test.main</em>.
   *
   * <p>This code is generated by the AgentCompiler. Emitter actions generate boolean events that
   * capture failure upon return, but otherwise return true and are run through runAsync.
   *
   * <p>Asynchronous suppliers return {@link java.util.concurrent.CompletableFuture} for their
   * target type. These have one exit point and contain no <code>fire</code> statements. Their
   * result is automatically posted to the event bus as a .thenApply consequence.
   *
   * <p>Function statements are blocking and run to completion.
   *
   * <p>No <em>return</em> statement, so returns false to prevent decommissioning. TODO all local
   * variables can be passed as final arguments instead of being in the scope. Mutability should be
   * a syntax error
   *
   * @param scope
   * @return true if the action was executed successfully and its child listeners should be removed.
   */
  private boolean main_0(AgentScope scope) {

    /* ------ begin setup code for the timer supplier reactive message, id = 1 ------ */
    // timer.in(15.s): time -> console.format("Sono le %s", time)

    /* ------ end setup code for the reactive message ------ */

    /* ------ timer supplier verb invocation with scope setting the ID for outgoing events ---- */
    var timer_1_duration =
        TimeDuration.of(
            15 * Time.Resolution.Type.SECOND.getMilliseconds(), Time.Resolution.Type.SECOND);
    var timer_1_time =
        TimeInstant.create(System.currentTimeMillis() + timer_1_duration.getMilliseconds());
    runSupplier(
        onEvent(
            scope,
            (e, s) -> {
              // --- code compiled from the action body after the timer verb
              CoreActorLibrary.Console.format(
                  s, "Passati 15 secondi: dovrebbero essere le %s\n", e.payload());
              // --- end of code
            },
            EventType.RETURN),
        s -> CoreActorLibrary.Timer.in(s, timer_1_duration, timer_1_time));

    /* ------ end of timer supplier verb invocation. RETURN disposes the listener. ------ */

    /* ------ begin setup code for the timer reactive message, id = 2 ------ */
    // emitter: sentence -> console.format("Emitter said %s", sentence)
    ;
    /* ------ end setup code for the reactive message ------ */

    runEmitter(
        onEvent(
            scope,
            (e, s) -> {
              // --- code compiled from the action body after the timer verb
              CoreActorLibrary.Console.format(s, "Emitter said %s\n", e.payload());
              // --- end of code
            },
            EventType.FIRE),
        this::emitter_2);

    return true;
  }

  /**
   * Named action <em>emitter</em> running in scope with action id == 2 compiled from line 14 of
   * <em>test.main</em>.
   *
   * <p>This code is generated by the AgentCompiler
   *
   * @param scope_emitter
   * @return
   */
  private boolean emitter_2(AgentScope scope_emitter) {

    /* ------ begin setup code for the timer reactive message, id = 3 ------ */
    // timer.random(step=10.s): time -> fire "dio puto"
    /* ------ end setup code for the reactive message ------ */
    /* ------ timer verb invocation with scope setting the ID for outgoing events ---- */
    /* ------ TODO document parameter mediation and assignment ------ */
    runEmitter(
        // this sets up the scope to react to
        onEvent(
            scope_emitter,
            (event, scope) -> {
              // --- code compiled from the action body after the timer verb
              scope.doFire("dio puto");
              // --- end of code
            },
            EventType.FIRE),
        s -> CoreActorLibrary.Timer.random(s, TimeUnit.SECONDS, 1));
    /* ------ end of timer verb invocation. Remember type of payload for matching upstream ------ */

    return true;
  }

  public static void main(String[] args) {

    var agent = new RuntimeAgentExample();
    Utils.CLI.create().with("start", c -> agent.run()).with("stop", c -> agent.stop()).run();
  }
}
