package org.integratedmodelling.klab.services.runtime.digitaltwin.scheduler;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;

/**
 * The <code>TimeEmitter</code> receives registrations from time event consumers specifying a start
 * and end time (in epoch milliseconds) and a resolution of activation, which is composed by a time
 * unit and a duration. The registration results in a long ID being returned; registrations that
 * would create events that overlap those generated by previous ones are not stored but the
 * pre-existing ID is returned instead.
 *
 * <p>The emitter has start() functions that starts the clock either in simulated or real time mode;
 * the clock will start at the earliest registration time and may end at the latest, or continue
 * until a set time (either mode) or indefinitely (real mode). New registrations can be added after
 * the clock has started: this can change the schedule for future event generation but will not
 * cause the emission of events in the past of the newly registered reactor.
 *
 * <p>Emission of an event results in the abstract #emitEvent callback being invoked, containing the
 * event ID, the time of start and end, and the list of registrations that are affected by the
 * event. Events are always full periods of time, with an epoch start and end, and should only be
 * emitted when their frequency and duration resonates with the resolution and phase of the
 * registration.
 *
 * <p>The emitter must be able to run in real time or in simulated time. A simulated time emitter
 * does not need to wait for the actual time to pass; a real time emitter must emit the events only
 * when the actual time event has been seen.
 *
 * <p>It must be possible to tell a simulated time emitter to switch to real time, starting at the
 * current system time or at a specified epoch time, even if it is already running. In that
 * situation the event emission for future events starts following the real-time schedule.
 *
 * <p>The state of the emitter, including all registrations, must be serializable as a JSON object
 * that can be stored externally as a parsimonious string.
 */
public class TimeEmitter implements AutoCloseable {

  private static final long UNBOUNDED = -1L;
  private static final long NO_CURRENT_TIME = Long.MIN_VALUE;

  private final Object lock = new Object();
  private final Map<Long, Registration> registrations = new LinkedHashMap<>();

  private long nextRegistrationId = 1L;
  private long lastEpochTime = -1;
  private long currentEpochTime = NO_CURRENT_TIME;
  private boolean clockRunning;
  private boolean realtimeMode;
  private long realtimeBaseEpochTime = NO_CURRENT_TIME;
  private long realtimeBaseWallTime = -1L;
  private ScheduledExecutorService realtimeExecutor;
  private ScheduledFuture<?> realtimeFuture;

  /** Create an empty time emitter for further specification. */
  public TimeEmitter() {}

  /**
   * A <code>Schedule</code> is a serializable object containing a summary of the overall schedule.
   * The state of the scheduler, including all existing registrations, must be reconstructable from
   * it.
   */
  public static final class Schedule implements Serializable {

    @Serial private static final long serialVersionUID = 1L;

    private final long nextRegistrationId;
    private final long lastEpochTime;
    private final long currentEpochTime;
    private final List<Registration> registrations;

    /** Create an empty schedule. */
    public Schedule() {
      this(1L, -1L, NO_CURRENT_TIME, List.of());
    }

    private Schedule(
        long nextRegistrationId,
        long lastEpochTime,
        long currentEpochTime,
        List<Registration> registrations) {
      this.nextRegistrationId = Math.max(1L, nextRegistrationId);
      this.lastEpochTime = lastEpochTime;
      this.currentEpochTime = currentEpochTime;
      this.registrations = List.copyOf(registrations);
    }

    public long getNextRegistrationId() {
      return nextRegistrationId;
    }

    public long getLastEpochTime() {
      return lastEpochTime;
    }

    public long getCurrentEpochTime() {
      return currentEpochTime;
    }

    public List<Registration> getRegistrations() {
      return registrations;
    }

    /** Serialize this schedule as compact JSON using only JDK functionality. */
    public String toJson() {
      var json = new StringBuilder(96 + registrations.size() * 96);
      json.append("{\"version\":1");
      json.append(",\"nextRegistrationId\":").append(nextRegistrationId);
      json.append(",\"lastEpochTime\":").append(lastEpochTime);
      json.append(",\"currentEpochTime\":").append(currentEpochTime);
      json.append(",\"registrations\":[");
      for (int i = 0; i < registrations.size(); i++) {
        var registration = registrations.get(i);
        if (i > 0) {
          json.append(',');
        }
        json.append('{');
        json.append("\"id\":").append(registration.id());
        json.append(",\"tStart\":").append(registration.tStart());
        json.append(",\"tEnd\":").append(registration.tEnd());
        json.append(",\"duration\":").append(registration.duration());
        json.append(",\"resolution\":");
        appendJsonString(json, registration.resolution().name());
        json.append('}');
      }
      json.append("]}");
      return json.toString();
    }

    /** Reconstruct a schedule from the JSON emitted by {@link #toJson()}. */
    public static Schedule fromJson(String json) {
      Objects.requireNonNull(json, "json");
      var root = Json.parseObject(json);
      var version = longField(root, "version", 1L);
      if (version != 1L) {
        throw new IllegalArgumentException("Unsupported TimeEmitter schedule version: " + version);
      }

      var registrations = new ArrayList<Registration>();
      var registrationObjects = root.get("registrations");
      if (registrationObjects instanceof List<?> list) {
        for (var item : list) {
          if (!(item instanceof Map<?, ?> rawMap)) {
            throw new IllegalArgumentException("Invalid registration in schedule JSON");
          }
          @SuppressWarnings("unchecked")
          var registration = (Map<String, Object>) rawMap;
          registrations.add(
              new Registration(
                  longField(registration, "id"),
                  longField(registration, "tStart"),
                  longField(registration, "tEnd"),
                  longField(registration, "duration"),
                  TimeUnit.valueOf(stringField(registration, "resolution"))));
        }
      }

      return new Schedule(
          longField(
              root,
              "nextRegistrationId",
              registrations.stream().mapToLong(Registration::id).max().orElse(0L) + 1L),
          longField(root, "lastEpochTime", -1L),
          longField(root, "currentEpochTime", NO_CURRENT_TIME),
          registrations);
    }
  }

  /**
   * Create a time emitter with the specified schedule; restart the clock at the point specified in
   * the schedule.
   *
   * @param schedule
   */
  public TimeEmitter(Schedule schedule) {
    Objects.requireNonNull(schedule, "schedule");
    synchronized (lock) {
      this.nextRegistrationId = schedule.getNextRegistrationId();
      this.lastEpochTime = schedule.getLastEpochTime();
      this.currentEpochTime = schedule.getCurrentEpochTime();
      for (var registration : schedule.getRegistrations()) {
        if (isValidRegistration(
            registration.tStart(),
            registration.tEnd(),
            registration.duration(),
            registration.resolution())) {
          this.registrations.put(registration.id(), registration);
          this.nextRegistrationId = Math.max(this.nextRegistrationId, registration.id() + 1L);
        }
      }
    }
  }

  /** Serializable description of one time reactor registration. */
  public record Registration(long id, long tStart, long tEnd, long duration, TimeUnit resolution)
      implements Serializable {

    @Serial private static final long serialVersionUID = 1L;

    public Registration {
      Objects.requireNonNull(resolution, "resolution");
    }

    public long periodMilliseconds() {
      return TimeEmitter.periodMilliseconds(duration, resolution);
    }
  }

  /**
   * Register a new time reactor with the emitter, starting at the specified epoch time and ending
   * at the specified epoch time unless the #end parameter is -1, which makes the registration not
   * end.
   *
   * <p>The duration and resolution are used to calculate the frequency of the time events affecting
   * this registration and any overlapping ones.
   *
   * <p>It must be possible to register a reactor with the same frequency and duration as an
   * existing one; if the start time makes it in phase with other, existing registrations, the
   * already registered ID should be returned and no changes to the schedule should be made.
   *
   * @return the ID of the registration, or -1 if the registration was not accepted.
   */
  public long register(long tStart, long tEnd, long duration, TimeUnit resolution) {
    if (!isValidRegistration(tStart, tEnd, duration, resolution)) {
      return -1L;
    }

    var period = periodMilliseconds(duration, resolution);
    synchronized (lock) {
      var logicalNow = realtimeMode ? logicalNowLocked() : currentEpochTime;
      if (clockRunning
          && logicalNow != NO_CURRENT_TIME
          && tEnd != UNBOUNDED
          && tEnd <= logicalNow) {
        return -1L;
      }

      for (var registration : registrations.values()) {
        if (sameCadence(registration, tStart, period)
            && eventRangesOverlap(registration, tStart, tEnd, period)) {
          return registration.id();
        }
      }

      var id = nextRegistrationId++;
      registrations.put(id, new Registration(id, tStart, tEnd, duration, resolution));
      scheduleNextRealtimeLocked();
      return id;
    }
  }

  /**
   * Unregister a time reactor, returning true if the reactor was found and removed. If no other
   * reactors that resonate with the frequency corresponding to the passed ID exists, no more events
   * should be emitted for that frequency.
   *
   * @param id
   * @return
   */
  public boolean unregister(long id) {
    synchronized (lock) {
      var removed = registrations.remove(id) != null;
      if (removed) {
        scheduleNextRealtimeLocked();
      }
      return removed;
    }
  }

  /**
   * TODO retrieve a serializable object containing a summary of the overall schedule, including
   * start/end times and resolutions.
   *
   * @return
   */
  public Schedule getSchedule() {
    synchronized (lock) {
      return new Schedule(
          nextRegistrationId,
          lastEpochTime,
          currentEpochTime,
          new ArrayList<>(registrations.values()));
    }
  }

  /**
   * This should be called if running in simulated time and the last epoch time is not known because
   * all registration had an end time of -1.
   *
   * @param epochTime
   */
  public void setLastEpochTime(long epochTime) {
    synchronized (lock) {
      this.lastEpochTime = epochTime;
    }
  }

  /**
   * Return the last epoch time that was set with {@link #setLastEpochTime(long)}.
   *
   * @return
   */
  public long getLastEpochTime() {
    synchronized (lock) {
      return this.lastEpochTime;
    }
  }

  /**
   * Return the current logical epoch time reached by the emitter, or {@link Long#MIN_VALUE} if the
   * clock has not been started yet.
   */
  public long getCurrentEpochTime() {
    synchronized (lock) {
      return currentEpochTime;
    }
  }

  public boolean isClockRunning() {
    synchronized (lock) {
      return clockRunning;
    }
  }

  public boolean isRealtimeMode() {
    synchronized (lock) {
      return realtimeMode;
    }
  }

  /**
   * Start the clock in simulated time mode. The schedule must still be available after this call.
   * The clock will start at the earliest registration time and end at the latest, unless {@link
   * #startRealtimeClock()} is called.
   *
   * <p>If all registrations were submitted with an unspecified end time, the clock should run until
   * a hard epoch time end is reached, established with {@link #setLastEpochTime(long)}. It is an
   * error to start a simulated clock with only unending registrations if the lastEpochTime isn't
   * set.
   */
  public void startSimulatedClock() {
    synchronized (lock) {
      cancelRealtimeLocked();
      realtimeMode = false;
      clockRunning = true;
      if (registrations.isEmpty()) {
        clockRunning = false;
        return;
      }
      if (currentEpochTime == NO_CURRENT_TIME) {
        currentEpochTime = earliestRegistrationStartLocked();
      }
    }

    try {
      while (true) {
        List<Emission> emissions;
        synchronized (lock) {
          if (!clockRunning || realtimeMode) {
            return;
          }
          var boundary = simulatedBoundaryLocked();
          emissions = nextEmissionsAfterLocked(currentEpochTime, boundary);
          if (emissions.isEmpty()) {
            clockRunning = false;
            return;
          }
          currentEpochTime = emissions.getLast().tEnd();
        }
        emitAll(emissions, false);
      }
    } catch (RuntimeException | Error e) {
      synchronized (lock) {
        if (!realtimeMode) {
          clockRunning = false;
        }
      }
      throw e;
    }
  }

  /**
   * Switch the clock to real time mode and start emitting events at the relevant resolutions. If
   * the clock is already running in simulated time, reschedule future events to run at the physical
   * time intervals corresponding to the registration.
   */
  public void startRealtimeClock() {
    long epochTime;
    synchronized (lock) {
      epochTime =
          clockRunning && !realtimeMode && currentEpochTime != NO_CURRENT_TIME
              ? currentEpochTime
              : System.currentTimeMillis();
    }
    startRealtimeClock(epochTime);
  }

  /**
   * Switch the clock to real time mode using the supplied logical epoch as "now"; future events are
   * emitted after the corresponding amount of physical time has elapsed.
   *
   * @param epochTime the logical epoch time represented by the current wall-clock instant
   */
  public void startRealtimeClock(long epochTime) {
    synchronized (lock) {
      cancelRealtimeLocked();
      clockRunning = true;
      realtimeMode = true;
      currentEpochTime = epochTime;
      realtimeBaseEpochTime = epochTime;
      realtimeBaseWallTime = System.currentTimeMillis();
      realtimeExecutor = Executors.newSingleThreadScheduledExecutor(daemonThreadFactory());
      scheduleNextRealtimeLocked();
    }
  }

  /** Stop the clock. The schedule must still be available after this call. */
  public void stopClock() {
    synchronized (lock) {
      clockRunning = false;
      realtimeMode = false;
      cancelRealtimeLocked();
    }
  }

  @Override
  public void close() {
    stopClock();
  }

  /**
   * Callback invoked when an event is emitted.
   *
   * @param tStart
   * @param tEnd
   * @param registrationIds all the registration IDs affected by the event. This should have at
   *     least one element as events are only emitted if any registration resonates with the
   *     schedule.
   */
  public void emitEvent(long tStart, long tEnd, long[] registrationIds) {}

  private void emitAll(List<Emission> emissions, boolean realtime) {
    for (var emission : emissions) {
      synchronized (lock) {
        if (!clockRunning || realtimeMode != realtime) {
          return;
        }
      }
      emitEvent(emission.tStart(), emission.tEnd(), emission.registrationIds().clone());
    }
  }

  private void emitRealtimeDue() {
    while (true) {
      List<Emission> emissions;
      synchronized (lock) {
        if (!clockRunning || !realtimeMode) {
          return;
        }
        var now = logicalNowLocked();
        emissions = nextEmissionsAfterLocked(currentEpochTime, now);
        if (emissions.isEmpty()) {
          currentEpochTime = maxEpoch(currentEpochTime, now);
          scheduleNextRealtimeLocked();
          return;
        }
        currentEpochTime = emissions.getLast().tEnd();
      }
      emitAll(emissions, true);
    }
  }

  private void scheduleNextRealtimeLocked() {
    if (!clockRunning
        || !realtimeMode
        || realtimeExecutor == null
        || realtimeExecutor.isShutdown()) {
      return;
    }
    if (realtimeFuture != null) {
      realtimeFuture.cancel(false);
      realtimeFuture = null;
    }
    var now = logicalNowLocked();
    var after = maxEpoch(currentEpochTime, now);
    var next = nextEmissionsAfterLocked(after, Long.MAX_VALUE);
    if (!next.isEmpty()) {
      var delay = Math.max(0L, next.getFirst().tEnd() - now);
      realtimeFuture =
          realtimeExecutor.schedule(this::emitRealtimeDue, delay, TimeUnit.MILLISECONDS);
    }
  }

  private List<Emission> nextEmissionsAfterLocked(long afterEpoch, long boundaryEpoch) {
    if (registrations.isEmpty() || boundaryEpoch == NO_CURRENT_TIME) {
      return List.of();
    }

    var earliestEnd = Long.MAX_VALUE;
    var candidates = new ArrayList<EventKey>();
    for (var registration : registrations.values()) {
      var candidate = nextCandidate(registration, afterEpoch, boundaryEpoch);
      if (candidate == null) {
        continue;
      }
      if (candidate.tEnd() < earliestEnd) {
        earliestEnd = candidate.tEnd();
        candidates.clear();
      }
      if (candidate.tEnd() == earliestEnd && !candidates.contains(candidate)) {
        candidates.add(candidate);
      }
    }

    if (candidates.isEmpty()) {
      return List.of();
    }

    candidates.sort(Comparator.comparingLong(EventKey::tStart).thenComparingLong(EventKey::tEnd));
    var emissions = new ArrayList<Emission>(candidates.size());
    for (var candidate : candidates) {
      var ids = new ArrayList<Long>();
      for (var registration : registrations.values()) {
        if (resonates(registration, candidate.tStart(), candidate.tEnd())) {
          ids.add(registration.id());
        }
      }
      if (!ids.isEmpty()) {
        emissions.add(new Emission(candidate.tStart(), candidate.tEnd(), toLongArray(ids)));
      }
    }
    return emissions;
  }

  private EventKey nextCandidate(Registration registration, long afterEpoch, long boundaryEpoch) {
    var period = registration.periodMilliseconds();
    var start = registration.tStart();
    var end = safeAdd(start, period);
    if (end == null) {
      return null;
    }

    if (afterEpoch != NO_CURRENT_TIME && end <= afterEpoch) {
      var delta = afterEpoch - registration.tStart();
      var steps = Math.max(0L, delta / period);
      var offset = safeMultiply(steps, period);
      if (offset == null) {
        return null;
      }
      var candidateStart = safeAdd(registration.tStart(), offset);
      if (candidateStart == null) {
        return null;
      }
      start = candidateStart;
      end = safeAdd(start, period);
      while (end != null && end <= afterEpoch) {
        start = end;
        end = safeAdd(start, period);
      }
      if (end == null) {
        return null;
      }
    }

    if (registration.tEnd() != UNBOUNDED && end > registration.tEnd()) {
      return null;
    }
    if (end > boundaryEpoch) {
      return null;
    }
    return new EventKey(start, end);
  }

  private boolean resonates(Registration registration, long eventStart, long eventEnd) {
    var period = registration.periodMilliseconds();
    return eventEnd - eventStart == period
        && eventStart >= registration.tStart()
        && (registration.tEnd() == UNBOUNDED || eventEnd <= registration.tEnd())
        && Math.floorMod(eventStart, period) == Math.floorMod(registration.tStart(), period);
  }

  private long simulatedBoundaryLocked() {
    var anyBounded = false;
    var anyUnbounded = false;
    var latest = NO_CURRENT_TIME;

    for (var registration : registrations.values()) {
      if (registration.tEnd() == UNBOUNDED) {
        anyUnbounded = true;
      } else {
        anyBounded = true;
        latest = maxEpoch(latest, registration.tEnd());
      }
    }

    if (!anyBounded && anyUnbounded) {
      if (lastEpochTime < 0L) {
        throw new IllegalStateException(
            "Cannot run a simulated TimeEmitter with only unbounded registrations until lastEpochTime is set");
      }
      return lastEpochTime;
    }

    if (anyUnbounded && lastEpochTime >= 0L) {
      latest = maxEpoch(latest, lastEpochTime);
    }
    return latest;
  }

  private long earliestRegistrationStartLocked() {
    return registrations.values().stream()
        .mapToLong(Registration::tStart)
        .min()
        .orElse(NO_CURRENT_TIME);
  }

  private long logicalNowLocked() {
    if (!realtimeMode || realtimeBaseEpochTime == NO_CURRENT_TIME || realtimeBaseWallTime < 0L) {
      return currentEpochTime;
    }
    var elapsed = Math.max(0L, System.currentTimeMillis() - realtimeBaseWallTime);
    var ret = safeAdd(realtimeBaseEpochTime, elapsed);
    return ret == null ? Long.MAX_VALUE : ret;
  }

  private void cancelRealtimeLocked() {
    if (realtimeFuture != null) {
      realtimeFuture.cancel(false);
      realtimeFuture = null;
    }
    if (realtimeExecutor != null) {
      realtimeExecutor.shutdownNow();
      realtimeExecutor = null;
    }
  }

  private static boolean isValidRegistration(
      long tStart, long tEnd, long duration, TimeUnit resolution) {
    if (resolution == null
        || duration <= 0L
        || tStart == NO_CURRENT_TIME
        || (tEnd != UNBOUNDED && tEnd <= tStart)) {
      return false;
    }
    try {
      var period = periodMilliseconds(duration, resolution);
      var firstEnd = safeAdd(tStart, period);
      return firstEnd != null && (tEnd == UNBOUNDED || firstEnd <= tEnd);
    } catch (IllegalArgumentException e) {
      return false;
    }
  }

  private static long periodMilliseconds(long duration, TimeUnit resolution) {
    var period = resolution.toMillis(duration);
    if (period <= 0L) {
      throw new IllegalArgumentException("TimeEmitter registrations must resolve to at least 1 ms");
    }
    return period;
  }

  private static boolean sameCadence(Registration registration, long tStart, long period) {
    return registration.periodMilliseconds() == period
        && Math.floorMod(registration.tStart(), period) == Math.floorMod(tStart, period);
  }

  private static boolean eventRangesOverlap(
      Registration registration, long tStart, long tEnd, long period) {
    var existingMax = lastEventStart(registration.tEnd(), period);
    var proposedMax = lastEventStart(tEnd, period);
    return Math.max(registration.tStart(), tStart) <= Math.min(existingMax, proposedMax);
  }

  private static long lastEventStart(long tEnd, long period) {
    return tEnd == UNBOUNDED ? Long.MAX_VALUE : tEnd - period;
  }

  private static long[] toLongArray(List<Long> values) {
    var ret = new long[values.size()];
    for (int i = 0; i < values.size(); i++) {
      ret[i] = values.get(i);
    }
    return ret;
  }

  private static long maxEpoch(long a, long b) {
    if (a == NO_CURRENT_TIME) {
      return b;
    }
    if (b == NO_CURRENT_TIME) {
      return a;
    }
    return Math.max(a, b);
  }

  private static Long safeAdd(long a, long b) {
    try {
      return Math.addExact(a, b);
    } catch (ArithmeticException e) {
      return null;
    }
  }

  private static Long safeMultiply(long a, long b) {
    try {
      return Math.multiplyExact(a, b);
    } catch (ArithmeticException e) {
      return null;
    }
  }

  private static ThreadFactory daemonThreadFactory() {
    return Thread.ofPlatform().daemon().name("klab-time-emitter-", 0).factory();
  }

  private static long longField(Map<String, Object> object, String fieldName) {
    var value = object.get(fieldName);
    if (value instanceof Number number) {
      return number.longValue();
    }
    throw new IllegalArgumentException("Missing or invalid numeric field: " + fieldName);
  }

  private static long longField(Map<String, Object> object, String fieldName, long defaultValue) {
    return object.containsKey(fieldName) ? longField(object, fieldName) : defaultValue;
  }

  private static String stringField(Map<String, Object> object, String fieldName) {
    var value = object.get(fieldName);
    if (value instanceof String string) {
      return string;
    }
    throw new IllegalArgumentException("Missing or invalid string field: " + fieldName);
  }

  private static void appendJsonString(StringBuilder json, String value) {
    json.append('"');
    for (int i = 0; i < value.length(); i++) {
      var c = value.charAt(i);
      switch (c) {
        case '"' -> json.append("\\\"");
        case '\\' -> json.append("\\\\");
        case '\b' -> json.append("\\b");
        case '\f' -> json.append("\\f");
        case '\n' -> json.append("\\n");
        case '\r' -> json.append("\\r");
        case '\t' -> json.append("\\t");
        default -> {
          if (c < 0x20) {
            json.append(String.format("\\u%04x", (int) c));
          } else {
            json.append(c);
          }
        }
      }
    }
    json.append('"');
  }

  private record EventKey(long tStart, long tEnd) {}

  private record Emission(long tStart, long tEnd, long[] registrationIds) {}

  private static final class Json {

    private final String text;
    private int offset;

    private Json(String text) {
      this.text = text;
    }

    static Map<String, Object> parseObject(String text) {
      var parser = new Json(text);
      var value = parser.parseValue();
      parser.skipWhitespace();
      if (parser.offset != parser.text.length()) {
        throw new IllegalArgumentException("Unexpected trailing data in JSON");
      }
      if (value instanceof Map<?, ?> rawMap) {
        @SuppressWarnings("unchecked")
        var map = (Map<String, Object>) rawMap;
        return map;
      }
      throw new IllegalArgumentException("Schedule JSON must be an object");
    }

    private Object parseValue() {
      skipWhitespace();
      if (offset >= text.length()) {
        throw new IllegalArgumentException("Unexpected end of JSON");
      }
      return switch (text.charAt(offset)) {
        case '{' -> parseMap();
        case '[' -> parseList();
        case '"' -> parseString();
        case 't' -> parseLiteral("true", Boolean.TRUE);
        case 'f' -> parseLiteral("false", Boolean.FALSE);
        case 'n' -> parseLiteral("null", null);
        default -> parseNumber();
      };
    }

    private Map<String, Object> parseMap() {
      expect('{');
      var ret = new LinkedHashMap<String, Object>();
      skipWhitespace();
      if (peek('}')) {
        offset++;
        return ret;
      }
      while (true) {
        var key = parseString();
        skipWhitespace();
        expect(':');
        ret.put(key, parseValue());
        skipWhitespace();
        if (peek('}')) {
          offset++;
          return ret;
        }
        expect(',');
      }
    }

    private List<Object> parseList() {
      expect('[');
      var ret = new ArrayList<>();
      skipWhitespace();
      if (peek(']')) {
        offset++;
        return ret;
      }
      while (true) {
        ret.add(parseValue());
        skipWhitespace();
        if (peek(']')) {
          offset++;
          return ret;
        }
        expect(',');
      }
    }

    private String parseString() {
      expect('"');
      var ret = new StringBuilder();
      while (offset < text.length()) {
        var c = text.charAt(offset++);
        if (c == '"') {
          return ret.toString();
        }
        if (c != '\\') {
          ret.append(c);
          continue;
        }
        if (offset >= text.length()) {
          throw new IllegalArgumentException("Invalid JSON escape");
        }
        var escaped = text.charAt(offset++);
        switch (escaped) {
          case '"' -> ret.append('"');
          case '\\' -> ret.append('\\');
          case '/' -> ret.append('/');
          case 'b' -> ret.append('\b');
          case 'f' -> ret.append('\f');
          case 'n' -> ret.append('\n');
          case 'r' -> ret.append('\r');
          case 't' -> ret.append('\t');
          case 'u' -> ret.append(parseUnicodeEscape());
          default -> throw new IllegalArgumentException("Invalid JSON escape: " + escaped);
        }
      }
      throw new IllegalArgumentException("Unterminated JSON string");
    }

    private char parseUnicodeEscape() {
      if (offset + 4 > text.length()) {
        throw new IllegalArgumentException("Invalid JSON unicode escape");
      }
      var hex = text.substring(offset, offset + 4);
      offset += 4;
      return (char) Integer.parseInt(hex, 16);
    }

    private Object parseLiteral(String literal, Object value) {
      if (!text.startsWith(literal, offset)) {
        throw new IllegalArgumentException("Invalid JSON literal at offset " + offset);
      }
      offset += literal.length();
      return value;
    }

    private Long parseNumber() {
      var start = offset;
      if (peek('-')) {
        offset++;
      }
      while (offset < text.length() && Character.isDigit(text.charAt(offset))) {
        offset++;
      }
      if (start == offset || (text.charAt(start) == '-' && start + 1 == offset)) {
        throw new IllegalArgumentException("Invalid JSON number at offset " + start);
      }
      return Long.parseLong(text.substring(start, offset));
    }

    private void skipWhitespace() {
      while (offset < text.length() && Character.isWhitespace(text.charAt(offset))) {
        offset++;
      }
    }

    private boolean peek(char c) {
      return offset < text.length() && text.charAt(offset) == c;
    }

    private void expect(char c) {
      skipWhitespace();
      if (!peek(c)) {
        throw new IllegalArgumentException("Expected '" + c + "' at offset " + offset);
      }
      offset++;
    }
  }
}
