server:
  address: 127.0.0.1
  port: 8080

logging:
  file:
    name: ${user.home}/.klab/services/graphdb/logs/graphdb.log
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] - ${PID:- } %-5level [%thread] --- %logger{39}: %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i"
      max-file-size: 10MB
      max-history: 10
      total-size-cap: 100MB

app:
  security:
    allowed-hosts:
      - 127.0.0.1
      - 0:0:0:0:0:0:0:1
      - ::1
  neo4j:
    host: 127.0.0.1
    bolt-port: 7687
    http-port: 7474
    data-directory: ${user.home}/.klab/services/graphdb/data
    plugins-directory: ${user.home}/.klab/services/graphdb/plugins
    config:
      server.directories.logs: ${user.home}/.klab/services/graphdb/logs
      dbms.logs.query.enabled: VERBOSE
      dbms.http_enabled_modules: BROWSER,REST
      dbms.security.procedures.unrestricted: '*'
