server:
  address: 127.0.0.1
  port: 8080

app:
  security:
    allowed-hosts:
      - 127.0.0.1
      - 0:0:0:0:0:0:0:1
      - ::1
  neo4j:
    host: 127.0.0.1
    bolt-port: 7687
    http-port: 7474
    data-directory: ./var/neo4j/data
    plugins-directory: ./var/neo4j/plugins
    config:
      server.directories.logs: ./var/neo4j/logs
      dbms.logs.query.enabled: VERBOSE
      dbms.security.procedures.unrestricted: '*'
