package org.integratedmodelling.klab.runtime.kactors.compiler;

import java.util.concurrent.TimeUnit;
import org.integratedmodelling.klab.api.exceptions.KlabActorException;
import org.integratedmodelling.klab.api.services.runtime.extension.Verb;
import org.integratedmodelling.klab.api.utils.Utils;
import org.integratedmodelling.klab.runtime.kactors.actors.runtime.AgentScope;
import org.integratedmodelling.klab.runtime.libraries.CoreActorLibrary;

///  # TO BE REMOVED - example translation of following k.Actors code:
///
///
/// ```
/// behavior test.main;
///
/// action main:
///    emitter: sentence -> console.format("Emitter said %s", sentence)
///
///  // an emitter (fires periodically, no return, continues firing)
/// action emitter:
///         timer.random(step=10.s): time -> fire "dio puto"
/// ```
///
/// This must be created by the actor compiler and compiled to a .class internally.
/// Actors that do not return must be run within an asynchronous container in order to work
/// properly.
///
/// Pattern for the compiler:
/// 1. Choose the base class and analyze the execution mode
/// 2. Override the necessary methods and the constructor
/// 3. In the constructor after calling super(),add any global state to the root scope
///
/// First pass should ensure that all identifiers and verbs are defined; build a catalog
/// of reactive forms and assign IDs to them proactively. Inferrable return types should be
/// remembered for parameter matching.
///
/// Compilation pass: for each action:
///   Compile each statement and add the code to a temporary buffer.
///     When statement is a reactive message call:
///         create a temporary buffer for the reactor setup code
///         assign action ID for the reactor scope, add scope creation to setup buffer
///         sink setup: filter for action ID, until TERMINATION events, subscribe
///           compile the reaction body within the subscription closure
///         add the asyncRun to the main code buffer
///
public class AgentExample extends AgentBase {

  public AgentExample() {
    super(null, null);
  }

  /* This code is generated by the AgentCompiler*/
  @Override
  protected ExitValue main(AgentScope initialScope) {

    // TODO if there's a behavior, the specialized scope class should get it to
    // analyze and set up any further data structures (UI, test plan etc).

    // TODO install any @handle messages for external message call

    // compile call to main_0 if there's a main action
    if (!main_0(initialScope)) {
      return ExitValue.failure(new KlabActorException(this, "main action failed to execute"));
    }
    // TODO should catch exceptions and return ExitValue.failure(exception)

    // end of main(). This must exit and the actor remains active depending on exec mode
    return ExitValue.success(0);
  }

  /* This code is generated by the AgentCompiler after analyzing the behavior*/
  @Override
  public Verb.Type getAgentExecutionMode() {
    return Verb.Type.EMITTER;
  }

  /**
   * Named action <em>main</em> with id == 0 compiled from line 10 of <em>test.main</em>.
   *
   * <p>This code is generated by the AgentCompiler
   *
   * <p>No <em>return</em> statement, so returns false to prevent decommissioning. TODO all local
   * variables can be passed as final arguments instead of being in the scope. Mutability should be
   * a syntax error
   *
   * @param scope
   * @return true if the action was executed successfully and its child listeners should be removed.
   */
  private boolean main_0(AgentScope scope) {

    /* ------ begin setup code for the timer reactive message, id = 1 ------ */
    // emitter: sentence -> console.format("Emitter said %s", sentence)
    var emitter_1_scope = scope.withId(1);
    this.eventBus
        .asFlux()
        // filter for events coming from timer
        .filter(event -> event.targetAction() == 1)
        // unsubscribe when the RETURN event is received (emitter returns)
        .takeUntil(it -> it.type().equals(EventType.TERMINATION))
        .subscribe(
            // event is fired by timer
            event -> {
              // --- code compiled from the action body after the timer verb
              CoreActorLibrary.Console.format(emitter_1_scope, "Emitter said %s\n", event.value());
              // --- end of code
            });
    /* ------ end setup code for the reactive message ------ */

    runAsync(emitter_1_scope, this::emitter_1);

    return true;
  }

  /**
   * Named action <em>emitter</em> running in scope with action id == 1 compiled from line 14 of
   * <em>test.main</em>.
   *
   * <p>This code is generated by the AgentCompiler
   *
   * @param scope_emitter
   * @return
   */
  private boolean emitter_1(AgentScope scope_emitter) {

    /* ------ begin setup code for the timer reactive message, id = 2 ------ */
    // timer.random(step=10.s): time -> fire "dio puto"
    var timer_2_scope = scope_emitter.withId(2);
    this.eventBus
        .asFlux()
        // filter for events coming from timer
        .filter(event -> event.targetAction() == 2)
        // unsubscribe when the RETURN event is received (emitter returns)
        .takeUntil(it -> it.type().equals(EventType.TERMINATION))
        .subscribe(
            // event is fired by timer
            event -> {
              // --- code compiled from the action body after the timer verb
              scope_emitter.doFire("dio puto");
              // --- end of code
            });
    /* ------ end setup code for the reactive message ------ */

    /* ------ timer verb invocation with scope setting the ID for outgoing events ---- */
    /* ------ TODO document parameter mediation and assignment ------ */
    runAsync(timer_2_scope, s -> CoreActorLibrary.Timer.random(s, TimeUnit.SECONDS, 1));
    /* ------ end of timer verb invocation. Remember type of payload for matching upstream ------ */

    return true;
  }

  public static void main(String[] args) {

    var agent = new AgentExample();
    Utils.CLI.create().with("start", c -> agent.run()).with("stop", c -> agent.stop()).run();
  }
}
