package org.integratedmodelling.klab.runtime.kactors.compiler;

import java.util.concurrent.TimeUnit;
import org.integratedmodelling.klab.api.exceptions.KlabActorException;
import org.integratedmodelling.klab.api.services.runtime.extension.Verb;
import org.integratedmodelling.klab.api.utils.Utils;
import org.integratedmodelling.klab.runtime.kactors.actors.runtime.AgentScope;
import org.integratedmodelling.klab.runtime.libraries.CoreActorLibrary;

///  # TO BE REMOVED - example translation of following k.Actors code:
///
///
/// ```

/// ```
////// behavior test.main;
/// ///
/// /// action main:
/// ///    emitter: sentence -> console.format("Emitter said %s", sentence)
/// ///
/// ///  // an emitter (fires periodically, no return, continues firing)
/// /// action emitter:
/// ///         timer.random(step=10.s): time -> fire "dio puto"
/// This must be created by the actor compiler and compiled to a .class internally.
/// Actors that do not return must be run within an asynchronous container to work
/// properly.
///
public class AgentExample extends AgentBase {

  public AgentExample() {
    super(null, null);
  }

  /* This code is generated by the AgentCompiler*/
  @Override
  protected ExitValue main(AgentScope initialScope) {

    // TODO if there's a behavior, the specialized scope class should get it to
    // analyze and set up any further data structures (UI, test plan etc).

    // TODO install any @handle messages for external message call

    // compile call to main_0 if there's a main action
    if (!main_0(initialScope)) {
      return ExitValue.failure(new KlabActorException(this, "main action failed to execute"));
    }
    // TODO should catch exceptions and return ExitValue.failure(exception)

    // end of main(). This must exit and the actor remains active depending on exec mode
    return ExitValue.success(0);
  }

  /* This code is generated by the AgentCompiler after analyzing the behavior*/
  @Override
  public Verb.Type getAgentExecutionMode() {
    return Verb.Type.EMITTER;
  }

  /**
   * Named action <em>main</em> with id == 0 compiled from line 10 of <em>test.main</em>.
   *
   * <p>This code is generated by the AgentCompiler. Emitter actions generate boolean events that
   * capture failure upon return, but otherwise return true and are run through runAsync.
   *
   * <p>Asynchronous suppliers return {@link java.util.concurrent.CompletableFuture} for their
   * target type. These have one exit point and contain no <code>fire</code> statements. Their
   * result is automatically posted to the event bus as a .thenApply consequence.
   *
   * Function statements are blocking and run to completion.
   *
   * <p>No <em>return</em> statement, so returns false to prevent decommissioning. TODO all local
   * variables can be passed as final arguments instead of being in the scope. Mutability should be
   * a syntax error
   *
   * @param scope
   * @return true if the action was executed successfully and its child listeners should be removed.
   */
  private boolean main_0(AgentScope scope) {

    /* ------ begin setup code for the timer reactive message, id = 1 ------ */
    // emitter: sentence -> console.format("Emitter said %s", sentence)
    var emitter_1_scope = scope.withId(1);
    onEvent(
        emitter_1_scope,
        event -> {
          // --- code compiled from the action body after the timer verb
          CoreActorLibrary.Console.format(emitter_1_scope, "Emitter said %s\n", event.value());
          // --- end of code
        },
        EventType.FIRE);
    /* ------ end setup code for the reactive message ------ */

    runAsync(emitter_1_scope, this::emitter_1);

    return true;
  }

  /**
   * Named action <em>emitter</em> running in scope with action id == 1 compiled from line 14 of
   * <em>test.main</em>.
   *
   * <p>This code is generated by the AgentCompiler
   *
   * @param scope_emitter
   * @return
   */
  private boolean emitter_1(AgentScope scope_emitter) {

    /* ------ begin setup code for the timer reactive message, id = 2 ------ */
    // timer.random(step=10.s): time -> fire "dio puto"
    var timer_2_scope = scope_emitter.withId(2);
    onEvent(
        timer_2_scope,
        event -> {
          // --- code compiled from the action body after the timer verb
          scope_emitter.doFire("dio puto");
          // --- end of code
        },
        EventType.FIRE);
    /* ------ end setup code for the reactive message ------ */

    /* ------ timer verb invocation with scope setting the ID for outgoing events ---- */
    /* ------ TODO document parameter mediation and assignment ------ */
    runAsync(timer_2_scope, s -> CoreActorLibrary.Timer.random(s, TimeUnit.SECONDS, 1));
    /* ------ end of timer verb invocation. Remember type of payload for matching upstream ------ */

    return true;
  }

  public static void main(String[] args) {

    var agent = new AgentExample();
    Utils.CLI.create().with("start", c -> agent.run()).with("stop", c -> agent.stop()).run();
  }
}
